Global:
  project_name: 'Demo_project'
  work_dir: cwd
  cache_dir: '_Cartridge'
  FEA_software: 'Nastran' # 'Ansys' or 'Nastran'=='MSC.Nastran' or 'Nx.Nastran'
  GPA_software: 'OrcaFlex' # 'OrcaFlex' or 'OpenFAST'

  output_pressure_unit: 'MPa'
  gravitational_acceleration:  9.80665 # m/s^2
  water_density :  1025  # water density(kg/m^3)
  water_depth :  300   # water depth(m)
  
ExternalSoftware:
  Nastran:
    mesh_dir: '_FEmodel'
    bdf_file: 'demo_model.dat'
    group_file: 'wetsurface.ses'
    StructureMorisonDict: morison_dict_structural.csv
    HydroMorisonDict: morison_dict_hydro.csv
   
    use_single_ses: true
    single_ses:
      ses_file: 'wetsurface.ses'
    length_unit: 'mm' # 'mm' or 'm'
    pressure_unit: 'MPa' # only 'MPa' currently
    cog:
      value: [0, 0, 20.5] # CoG location based on nastran model coordinate (keel, center of hull)
      unit: m
    underwater_only: true

  OrcaFlex:
    folder_name: 'FLS\NTM_V11_WndDir00_Hs4.5_Tp9.0_Gm2.4_Dir0_Cur0.8_CurDir0_Nac0_EndT4500_R0'
    time_history_filename: 'OrcaFlex_model.out'
    diffraction_hull_offset_effect: false
    wave_components_filename: FLS\NTM_V11_WndDir00_Hs4.5_Tp9.0_Gm2.4_Dir0_Cur0.8_CurDir0_Nac0_EndT4500_R0\waveinfo_wavecomp.inp
    cog:
      value: [0, 0, 5.5] # CoG location based on global coordinate (MWL, center of hull)
      unit: m
    heading: 0.0

Workflow:
  # =========================================================================== #
  #   Synthesize stress RAO from FEA and time history load from OpenFAST
  # =========================================================================== #
  4.synthesis:
    execute: false
    stress_rao_dir: _Cartridge
    synthesize_stress: true
    layer: top # ['middle', 'top', 'bottom']
    stress_file_extension: .op2
    output_dir: 'FLS/TRUST/synth'
    load_components_to_synthesize:
      diffraction: true
      radiation: true
      hydrostatic: true
      acceleration: true
      wind: true
      mooring: true
      morison: true
    batch_size: 100
    start_time: 0.0     # [s]
    end_time: 4500.0 # [s]
    resample_time_interval: 0.4 # [s]
    max_frequency: 5.0 # [Hz]
    lrfd_static: 1.00 # default is 1.0
    lrfd_dyn: 1.00   # default is 1.0

  # =========================================================================== #
  #   Strength Analysis analysis of the synthesized stress 
  # =========================================================================== #
  5.strength_analysis:
    execute: false
    output_dir: 'ULS/TRUST'
    type: max          #  'weibull_max' or  'max'
    start_time: 600.0
    end_time: 4200.0
    write_vtk: true
    write_f06: true

  # =========================================================================== #
  #   Fatigue analysis of the synthesized stress 
  # =========================================================================== #
  6.fatigue_analysis:
    execute: false
    output_dir: 'FLS/TRUST'
    start_time: 600.0
    end_time: 4200.0
    skip_steps: 0
    # Database file for S-N curves
    SN_curve_database: '_FEmodel\sncurve_library.csv'
    # Is the S-N curve single-slope? If dual-slope, set it to False
    single_slope: false
    element_SN_info: '_FEmodel\elem_sncurve_template.csv'
    write_vtk: true
    write_PR_stress_timeseries: false
